### ISSUE TITLE
Unsupported export count 69

### ISSUE THREAD

**Issue by LaneRendell** [jordanbtucker/ff7r-data-editor#4]
Your issue may already be reported.
Please search on the [issue tracker](https://github.com/jordanbtucker/ff7r-data-editor/issues) before creating one.

## Error Message
Unsupported export count 69

## Expected Behavior
File opens

## Actual Behavior
Error stack

## Steps to Reproduce the Problem
1. Open EndGameMode.uasset
2.
3.

## Error Stack
```
Error: Unsupported export count 69
    at UAsset.readHeader (C:\Users\Charles\Desktop\ff7rmods\Tools\ff7r-data-editor-win32-x64\resources\app\lib\uasset.js:75:13)
    at UAsset.read (C:\Users\Charles\Desktop\ff7rmods\Tools\ff7r-data-editor-win32-x64\resources\app\lib\uasset.js:22:10)
    at async UPackage.read (C:\Users\Charles\Desktop\ff7rmods\Tools\ff7r-data-editor-win32-x64\resources\app\lib\upackage.js:25:5)
    at async IpcMainImpl.openUPackage (C:\Users\Charles\Desktop\ff7rmods\Tools\ff7r-data-editor-win32-x64\resources\app\main\index.js:153:7)
```

## Specifications
- **Version:** 1.0.0-b.8
- **Platform:** win32 / Windows 10 Pro

**Comment by jordanbtucker** [comment]
Thanks for the report. Currently, this tool only works with files in `End\Content\GameContents\DataObject`.
